@startuml

fsmDescription: Описание машины состояний (*.js)
template: Шаблон выходного файла (text)
output: Генерированный файл
output: *.cs
output: *.h && *.cpp
output: *.png
output: & etc. (use your own templates)
fsmDescription --> output
template --> output

@enduml
